pipeline {
    agent any
    
    tools {
        terraform 'Terraform'
    }
    
    stages{
         stage('Git Checkout') {
            steps{
                git 'https://github.com/shashankreddya/testgit'
            }
        }
        
        stage('Terraform Init') {
            steps{
                sh 'terraform init'
            }
        }
        
        stage('Terraform Plan') {
            steps{
                sh 'terraform plan -out tfplan '
                sh 'terraform show -no-color tfplan > tfplan.txt'
            }
        }
        
        stage('Approval') {
           when {
               not {
                   equals expected: true, actual: params.autoApprove
               }
           }

           steps {
               script {
                    def plan = readFile 'tfplan.txt'
                    input message: "Do you want to apply the plan?",
                    parameters: [text(name: 'Plan', description: 'Please review the plan', defaultValue: plan)]
               }
           }
       }
        
        stage('Terraform Apply') {
            steps{
                sh 'terraform apply -input=false tfplan'
            }
        }
    }
    
    
}
